import LanguageCode from "./languageCode";

const langCodes: Array<LanguageCode> = [
	{ text: "Afrikaans", code: "af" },
	{ text: "Albanian", code: "sq" },
	{ text: "Amharic", code: "am" },
	{ text: "Arabic", code: "ar" },
	{ text: "Armenian", code: "hy" },
	{ text: "Assamese", code: "as" },
	{ text: "Azerbaijani", code: "" },
	{ text: "Bangla", code: "bn" },
	{ text: "Bashkir", code: "ba" },
	{ text: "Bosnian (Latin)", code: "bs" },
	{ text: "Bulgarian", code: "bg" },
	{ text: "Cantonese (Traditional)", code: "yue" },
	{ text: "Catalan", code: "ca" },
	{ text: "Chinese (Literary)", code: "lzh" },
	{ text: "Chinese Simplified", code: "zh-Hans" },
	{ text: "Chinese Traditional", code: "zh-Hant" },
	{ text: "Croatian", code: "hr" },
	{ text: "Czech", code: "cs" },
	{ text: "Danish", code: "da" },
	{ text: "Dari", code: "prs" },
	{ text: "Divehi", code: "dv" },
	{ text: "Dutch", code: "nl" },
	{ text: "English", code: "en" },
	{ text: "Estonian", code: "et" },
	{ text: "Fijian", code: "fj" },
	{ text: "Filipino", code: "fil" },
	{ text: "Finnish", code: "fi" },
	{ text: "French", code: "fr" },
	{ text: "French (Canada)", code: "fr-ca" },
	{ text: "Georgian", code: "ka" },
	{ text: "German", code: "de" },
	{ text: "Greek", code: "el" },
	{ text: "Gujarati", code: "gu" },
	{ text: "Haitian Creole", code: "ht" },
	{ text: "Hebrew", code: "he" },
	{ text: "Hindi", code: "hi" },
	{ text: "Hmong Daw", code: "mww" },
	{ text: "Hungarian", code: "hu" },
	{ text: "Icelandic", code: "is" },
	{ text: "Indonesian", code: "id" },
	{ text: "Inuktitut", code: "iu" },
	{ text: "Irish", code: "ga" },
	{ text: "Italian", code: "it" },
	{ text: "Japanese", code: "ja" },
	{ text: "Kannada", code: "kn" },
	{ text: "Kazakh", code: "kk" },
	{ text: "Khmer", code: "km" },
	{ text: "Klingon", code: "tlh-Latn" },
	{ text: "Klingon (plqaD)", code: "tlh-Piqd" },
	{ text: "Korean", code: "ko" },
	{ text: "Kurdish (Central)", code: "ku" },
	{ text: "Kurdish (Northern)", code: "kmr" },
	{ text: "Kyrgyz", code: "ky" },
	{ text: "Lao", code: "lo" },
	{ text: "Latvian", code: "lv" },
	{ text: "Lithuanian", code: "lt" },
	{ text: "Macedonian", code: "mk" },
	{ text: "Malagasy", code: "mg" },
	{ text: "Malay", code: "ms" },
	{ text: "Malayalam", code: "ml" },
	{ text: "Maltese", code: "mt" },
	{ text: "Maori", code: "mi" },
	{ text: "Marathi", code: "mr" },
	{ text: "Mongolian (Cyrillic)", code: "mn-Cyrl" },
	{ text: "Mongolian (Traditional)", code: "mn-Mong" },
	{ text: "Myanmar", code: "my" },
	{ text: "Nepali", code: "ne" },
	{ text: "Norwegian", code: "nb" },
	{ text: "Odia", code: "or" },
	{ text: "Pashto", code: "ps" },
	{ text: "Persian", code: "fa" },
	{ text: "Polish", code: "pl" },
	{ text: "Portuguese (Brazil)", code: "pt" },
	{ text: "Portuguese (Portugal)", code: "pt-pt" },
	{ text: "Punjabi", code: "pa" },
	{ text: "Queretaro Otomi", code: "otq" },
	{ text: "Romanian", code: "ro" },
	{ text: "Russian", code: "ru" },
	{ text: "Samoan", code: "sm" },
	{ text: "Serbian (Cyrillic)", code: "sr-Cyrl" },
	{ text: "Serbian (Latin)", code: "sr-Latn" },
	{ text: "Slovak", code: "sk" },
	{ text: "Slovenian", code: "sl" },
	{ text: "Spanish", code: "es" },
	{ text: "Swahili", code: "sw" },
	{ text: "Swedish", code: "sv" },
	{ text: "Tahitian", code: "ty" },
	{ text: "Tamil", code: "ta" },
	{ text: "Tatar", code: "tt" },
	{ text: "Telugu", code: "te" },
	{ text: "Thai", code: "th" },
	{ text: "Tibetan", code: "bo" },
	{ text: "Tigrinya", code: "ti" },
	{ text: "Tongan", code: "to" },
	{ text: "Turkish", code: "tr" },
	{ text: "Turkmen", code: "tk" },
	{ text: "Ukrainian", code: "uk" },
	{ text: "Urdu", code: "ur" },
	{ text: "Uyghur", code: "ug" },
	{ text: "Uzbek (Latin)", code: "uz" },
	{ text: "Vietnamese", code: "vi" },
	{ text: "Welsh", code: "cy" },
	{ text: "Yucatec Maya", code: "yua" },
];

export default langCodes;
