import RegionCode from "./regionCode";

const regions: Array<RegionCode> = [
    { text: "Global", code: "global" },
    { text: "East Asia", code: "eastasia" },
    { text: "Southeast Asia", code: "southeastasia" },
    { text: "Central US", code: "centralus" },
    { text: "East US", code: "eastus" },
    { text: "East US 2", code: "eastus2" },
    { text: "West US", code: "westus" },
    { text: "North Central US", code: "northcentralus" },
    { text: "South Central US", code: "southcentralus" },
    { text: "North Europe", code: "northeurope" },
    { text: "West Europe", code: "westeurope" },
    { text: "Japan West", code: "japanwest" },
    { text: "Japan East", code: "japaneast" },
    { text: "Brazil South", code: "brazilsouth" },
    { text: "Australia East", code: "australiaeast" },
    { text: "Australia Southeast", code: "australiasoutheast" },
    { text: "South India", code: "southindia" },
    { text: "Central India", code: "centralindia" },
    { text: "West India", code: "westindia" },
    { text: "Canada Central", code: "canadacentral" },
    { text: "Canada East", code: "canadaeast" },
    { text: "UK South", code: "uksouth" },
    { text: "UK West", code: "ukwest" },
    { text: "West Central US", code: "westcentralus" },
    { text: "West US 2", code: "westus2" },
    { text: "Korea Central", code: "koreacentral" },
    { text: "Korea South", code: "koreasouth" },
    { text: "France Central", code: "francecentral" },
    { text: "France South", code: "francesouth" },
    { text: "Australia Central", code: "australiacentral" },
    { text: "Australia Central 2", code: "australiacentral2" },
    { text: "UAE Central", code: "uaecentral" },
    { text: "UAE North", code: "uaenorth" },
    { text: "South Africa North", code: "southafricanorth" },
    { text: "South Africa West", code: "southafricawest" },
    { text: "Switzerland North", code: "switzerlandnorth" },
    { text: "Switzerland West", code: "switzerlandwest" },
    { text: "Germany North", code: "germanynorth" },
    { text: "Germany West Central", code: "germanywestcentral" },
    { text: "Norway West", code: "norwaywest" },
    { text: "Norway East", code: "norwayeast" }
];

export default regions;